/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.QueryCriteriaInvoiceType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param subjectType 
 * @param type 
 * @param invoicingDateFrom yyyy-MM-dd'T'HH:mm:ss | minimum date range is 2022-01-01
 * @param invoicingDateTo yyyy-MM-dd'T'HH:mm:ss | maximum date range is current time (+ max 6 hours), the difference between date field and #invoicingDateFrom cannot be greater than 24 months, date field cannot be before #invoicingDateFrom
 */

@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown=true)

data class QueryCriteriaInvoiceRangeType (

    @Json(name = "subjectType")
    override var subjectType: QueryCriteriaInvoiceType.SubjectType,

    @Json(name = "type")
    override var type: kotlin.String,

    /* yyyy-MM-dd'T'HH:mm:ss | minimum date range is 2022-01-01 */
    @Json(name = "invoicingDateFrom")
    var invoicingDateFrom: java.time.OffsetDateTime,

    /* yyyy-MM-dd'T'HH:mm:ss | maximum date range is current time (+ max 6 hours), the difference between date field and #invoicingDateFrom cannot be greater than 24 months, date field cannot be before #invoicingDateFrom */
    @Json(name = "invoicingDateTo")
    var invoicingDateTo: java.time.OffsetDateTime

) : QueryCriteriaInvoiceType {


}

