/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.V2QueryCriteriaInvoiceType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param queryCriteria 
 */

@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown=true)

data class V2QueryInvoiceRequest (

    @Json(name = "queryCriteria")
    var queryCriteria: V2QueryCriteriaInvoiceRangeType

) {


}

