/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param subjectType 
 * @param type 
 */

@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown=true)

interface V2QueryCriteriaInvoiceType {

    @Json(name = "subjectType")
    var subjectType: V2QueryCriteriaInvoiceType.SubjectType
    @Json(name = "type")
    var type: kotlin.String
    /**
     * 
     *
     * Values: subject1,subject2,subject3,subjectAuthorized
     */
    @JsonClass(generateAdapter = false)
    enum class SubjectType(val value: kotlin.String) {
        @Json(name = "subject1") subject1("subject1"),
        @Json(name = "subject2") subject2("subject2"),
        @Json(name = "subject3") subject3("subject3"),
        @Json(name = "subjectAuthorized") subjectAuthorized("subjectAuthorized");
    }

}

